### ISSUE TITLE
Error in countSpecies: incorrect number of dimensions

### ISSUE THREAD

**Issue by SvitlanaLukicheva** [GLBRC/sppIDer#1]
Hello,

I am trying to use sppIDer to study the introgression between two sister species of leaf beetles.

I first combined their genomes with `combineRefGenomes.py` script and then tried to use it with `sppIDer.py`. But I got the following error:

`[bwt_restore_sa] fail to open file 'REF.fasta.sa' : No such file or directory`

Indeed, the .sa file wasn't produced. So I ran `bwa index` on my combined genome and used the resulting files with `sppIDer.py`. But this time I have another error:

`Error in countSpecies[1, 1] : incorrect number of dimensions`

Do you have any idea how to solve this problem?

Thank you in advance.

**Comment by qlangdon** [comment]
Hi Svitlana,
I know which step this error came from. Do you have a file called XXX_MQ.txt, with the columns "Species	MQscore	count"? The error has to do with parsing this file so making sure it exists is the first step. 
I think this error has nothing to do with the issue you had with creating the reference. I have never seen that error before, but it looks like you found a workaround for it. 
Best, 
Quinn

**Comment by SvitlanaLukicheva** [comment]
Hello qlangdon, thank you for your quick response!!

Yes this file exists and its content is the following:
```
Species	MQscore	count
*	0	0
```

I suppose it shouldn't have zeros.. do you have an idea why the content of this file is bad?

**Comment by qlangdon** [comment]
This file should have multiple lines, with the name of the reference species and how many reads map at different Mapping Qualities (MQ). This file is built by parsing the *.sam file. The *.sam should be quite large and contain information about the reference contigs and the mapped reads. The next test will to be to check if your *.sam follows this format. https://samtools.github.io/hts-specs/SAMv1.pdf

**Comment by SvitlanaLukicheva** [comment]
You are right, the problem is caused by my SAM file, which is empty. BWA stops after 15 seconds, but I don't see any error message in the output:

```
C:\Users\Administrateur\Desktop\sppIDer>docker run --rm -it --mount type=bind,src=C:\Users/Administrateur/Desktop/sppIDer,target=/tmp/sppIDer/working glbrc/sppider sppIDer.py --out B5 --ref REF.fasta --r1 B5_R1.fastq --r2 B5_R2.fastq
Read1=B5_R1.fastq
Read2=B5_R2.fastq
BWA complete
Elapsed time: 15 secs
SAMTOOLS complete
Elapsed time: 15 secs
0.0128910541534 secs

Parsed SAM file
Elapsed time: 15 secs
Loading required package: ggplot2
Error in countSpecies[1, 1] : incorrect number of dimensions
Execution halted
```

Maybe I can create the SAM file myself and then give it to sppIDer?

**Comment by qlangdon** [comment]
This error may actually be rooted in the first error you got about the *.fasta.sa not being created. If something is wrong with the combination reference it would affect BWA running. Can you see what files combineRefGenomes.py created? If it did not create *.fasta.sa there may have been other issues.

**Comment by SvitlanaLukicheva** [comment]
Thank you again for helping me!!

Here are the files created by combineRefGenomes.py:

```
$ ls -l
total 11468165
-rwx------+ 1 Administrateur Aucun    1221933  4 juil. 17:50 comboLength_REF.fasta.txt
-rwx------+ 1 Administrateur Aucun 1972169086  3 mai    2018 gi_masurca.fa
-rwx------+ 1 Administrateur Aucun 1972127758 13 mars  16:41 gq_wtdbg.fa
-rwx------+ 1 Administrateur Aucun         42 21 juin  11:37 KEY.txt
-rwx------+ 1 Administrateur Aucun 3896797016  4 juil. 17:50 REF.fasta
-rwx------+ 1 Administrateur Aucun      26602  4 juil. 17:51 REF.fasta.amb
-rwx------+ 1 Administrateur Aucun    2576046  4 juil. 17:51 REF.fasta.ann
-rwx------+ 1 Administrateur Aucun 1947912560  5 juil. 11:40 REF.fasta.bwt
-rwx------+ 1 Administrateur Aucun    2640651  5 juil. 11:41 REF.fasta.fai
-rwx------+ 1 Administrateur Aucun 1947912520  4 juil. 17:51 REF.fasta.pac
```

And if it can help, this is the output of combineRefGenomes.py:

```
C:\Users\Administrateur\Desktop\sppIDer\ref_test>docker run --rm -it --mount type=bind,src=C:\Users/Administrateur/Desktop/sppIDer/ref_test,target=/tmp/sppIDer/working glbrc/sppider combineRefGenomes.py --out REF.fasta --key KEY.txt
[bwa_index] Pack FASTA... 22.26 sec
[bwa_index] Construct BWT for the packed sequence...
[BWTIncCreate] textLength=7791650072, availableWord=560249264
[BWTIncConstructFromPacked] 10 iterations done. 99999992 characters processed.
...
[BWTIncConstructFromPacked] 840 iterations done. 7778205272 characters processed.
[bwt_gen] Finished constructing BWT in 847 iterations.
[bwa_index] 6785.27 seconds elapse.
[bwa_index] Update BWT...
```

**Comment by qlangdon** [comment]
So I think the ultimate problem is that one step of combinRefGenomes.py is not running for some reason. If you can try running:

`/opt/bifxapps/bin/samtools faidx REF.fasta`

This should create the missing *sa file and, maybe, fix some of the downstream issues.

**Comment by SvitlanaLukicheva** [comment]
This step creates the *.fai file and interestingly it was already created by combineRefGenomes.py. As well as most of files created by `bwa index` command.

I think my problem is caused by `bwa` and not by sppIDer. `bwa index` is partially executed in combineRefGenomes.py, but at the end it stops for some reason and some files are not produced. And then, even if I manually create missing files from the first step, `bwa mem` fails in sppIDer.py. And the problem is that I don't see any error message to understand what happens.

Could it be possible that my problem is related to the fact that I run Docker on Windows?

Is there a way to manually inject the *.sam file to sppIDer.py?

**Comment by SvitlanaLukicheva** [comment]
Hello,

I finally solved my problem by downloading the scripts and running them on a cluster, without using Docker and now it works. The combineRefGenoms step created all the required files and there is no more error message in sppIDer step.

Thank you again for your help!

**Comment by wuxe-123** [comment]
Hello! I have also encountered this problem: Error in countSpecies[1, 1] : incorrect number of dimensions. Could you please tell me the specific solution?
